export const GET_LOAN_REQUEST = "GET_LOAN_REQUEST";
export const GET_LOAN_SUCCESS = "GET_LOAN_SUCCESS";
export const GET_LOAN_FAIL = "GET_LOAN_FAIL";

export const SET_LOAN = "SET_LOAN";

export const GET_MYLOAN_REQUEST = "GET_MYLOAN_REQUEST";
export const GET_MYLOAN_SUCCESS = "GET_MYLOAN_SUCCESS";
export const GET_MYLOAN_FAIL = "GET_MYLOAN_FAIL";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const USER_REG_REQUEST = "USER_REG_REQUEST";
export const USER_REG_SUCCESS = "USER_REG_SUCCESS";
export const USER_REG_FAIL = "USER_REG_FAIL";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const GET_APPLICATION_REQUEST = "GET_APPLICATION_REQUEST";
export const GET_APPLICATION_SUCCESS = "GET_APPLICATION_SUCCESS";
export const GET_APPLICATION_FAIL = "GET_APPLICATION_FAIL";

export const APPLICATION_FORM_REQUEST = "APPLICATION_FORM_REQUEST";
export const GET_REG_FORM = "GET_REG_FORM";
export const HIDE_REG_FORM = "HIDE_REG_FORM";

export const CREATE_APPLICATION_REQUEST = "CREATE_APPLICATION_REQUEST";
export const CREATE_APPLICATION_SUCCESS = "CREATE_APPLICATION_SUCCESS";
export const CREATE_APPLICATION_FAIL = "CREATE_APPLICATION_FAIL";

export const GET_REG_FORM_REQUEST = "GET_REG_FORM_REQUEST";
